---
apiVersion: v1
kind: Service
metadata:
 name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
   - port: 80
     targetPort: https
  selector:
    service: ambassador

