---
apiVersion: v1
kind: Service
metadata:
 name: ambassador
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
   - port: 443
     targetPort: https
  selector:
    service: ambassador

