---
apiVersion: v1
kind: Service
metadata:
 name: ambassador
 labels:
    app.kubernetes.io/component: ambassador-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
   - port: 443
     targetPort: https
  selector:
    service: ambassador

